services:
  - type: web
    name: roblox-replay-system
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p templates static
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src
      sizeGB: 1 